# ════════════════════════════════════════
# APPLICATION
# ════════════════════════════════════════
spring.application.name=JobKmer
server.port=8081

# ════════════════════════════════════════
# POSTGRESQL
# ════════════════════════════════════════
spring.datasource.url=jdbc:postgresql://localhost:5432/JobKmerDb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ════════════════════════════════════════
# JPA / HIBERNATE
# ════════════════════════════════════════
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ════════════════════════════════════════
# AUTRES
# ════════════════════════════════════════
file.upload.dir=./uploads
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.security=DEBUG

# ════════════════════════════════════════
# JWT
# ════════════════════════════════════════
application.security.jwt.secret-key=voiciUneVraieCleBase64De32CaractdresMinimum1234567890AB